name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest mypy

      - name: Run flake8
        run: python -m flake8 src/

      - name: Run pytest
        run: pytest

      - name: Run mypy
        run: mypy

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install Node dependencies
        run: npm ci

      - name: Install Node devDependencies
        run: npm install --only=dev

      - name: Lint JS
        run: npm run lint:js

      - name: Run Jest
        run: npx jest --ci --passWithNoTests

      - name: Build Phaser project
        run: npm run build

      - name: Deploy GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
